- cleaning
Changed files:
    gopherd.init -> 1.2

diff --git a/gopherd.init b/gopherd.init
--- a/gopherd.init
+++ b/gopherd.init
@@ -1,19 +1,55 @@
 #!/bin/sh
+#
+# Startup script for GoFish
+#
+# chkconfig:	345 86 14
+# description:	GoFish is a simple gopher / web server.
+# processname:	gopherd
+# pidfile:	/var/run/gopherd.pid
+# config:	/etc/gofish.conf
 
 # Source function library.
 . /etc/rc.d/init.d/functions
 
+# Get network config
+. /etc/sysconfig/network
+
+if is_yes "${NETWORKING}"; then
+	if [ ! -f /var/lock/subsys/network ]; then
+		msg_network_down gopherd
+		exit 1
+	fi
+else
+	exit 0
+fi
+
 # See how we were called.
 case "$1" in
   start)
-	msg_starting gopherd
-	daemon /usr/sbin/gopherd -d
-	touch /var/lock/subsys/gopherd
+	if [ ! -f /var/lock/subsys/gopherd ]; then
+		msg_starting gopherd
+		# daemon gopherd -d	# gopherd writes to terminal ... 
+		busy
+		termput hpa 45
+		gopherd -d		# no error code returned even if fails
+		sleep 1
+		ok
+		touch /var/lock/subsys/gopherd
+	else
+		msg_already_running gopherd
+		exit 1
+	fi
 	;;
   stop)
-	msg_stopping gopherd
-	killproc gopherd
-	rm -f /var/lock/subsys/gopherd
+	if [ -f /var/lock/subsys/gopherd ]; then
+		msg_stopping gopherd
+		killproc gopherd
+		rm -f /var/lock/subsys/gopherd
+		rm -f /var/run/gopherd.pid
+	else
+		msg_not_running gopherd
+		exit 1
+	fi
 	;;
   status)
 	status gopherd
@@ -23,6 +59,8 @@ case "$1" in
 	$0 start
 	;;
   *)
-	msg_usage "$0 {start|stop|status|restart|reload}"
+	msg_usage "$0 {start|stop|restart|reload|status}"
 	exit 1
 esac
+
+exit 0
